spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bit_test
    username: bit
    password: bit
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    sql.init.mode: alway